#! /bin/sh
# Copyright © 2016 Shawn Baker using the MIT License.

# get the parameters
if [ $# -ne 2 ]; then
	echo usage: $(basename $0) address port
	exit 1
fi
ADDRESS=$1
PORT=$2

while [ true ]; do
	raspivid -n -ih -t 0 -rot 0 -w 1280 -h 720 -fps 15 -b 1000000 -o - | multicat /dev/stdin $ADDRESS:$PORT
	sleep 1;
done
